vich_uploader:
    db_driver: orm

    mappings:
#        [entity_name]:
#            uri_prefix: /images/[entity_name]
#            upload_destination: '%kernel.project_dir%/public/images/[entity_name]'
        locatie:
            uri_prefix: /images/locatie
            upload_destination: '%kernel.project_dir%/public/images/locatie'
